# This policy verifies the installation of the official & supported version of
# the IBM CloudPak for Data Operator on the managed clusters.
#
# If set to "enforce" it'll install the operator.
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-ibm-cloudpak-data-operator
  annotations:
    policy.open-cluster-management.io/standards: ACME-Standards
    policy.open-cluster-management.io/categories: Operators-Install
    policy.open-cluster-management.io/controls: IBM CloudPak for Data
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
#    - objectDefinition:
#        apiVersion: policy.open-cluster-management.io/v1
#        kind: ConfigurationPolicy
#        metadata: ibm-cloudpak-operator-operator-group
#        spec:
#          remediationAction: enforce
#          severity: high
#          object-templates:
#            - complianceType: musthave
#              objectDefinition:
#                apiVersion: operators.coreos.com/v1
#                kind: OperatorGroup
#                metadata:
#                  name: ibm-cloudpak-operator
#                  namespace: openshift-operators
#                spec:
#                  targetNamespaces:
#                    - openshift-operators
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ibm-cloudpak-data-operator-subscription
        spec:
          remediationAction: enforce  # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: cpd-platform-operator
                  namespace: ibm-cp4s-data
                spec:
                  installPlanApproval: Automatic
                  name: cpd-platform-operator
                  source: ibm-operator-catalog
                  sourceNamespace: openshift-marketplace
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-ibm-cloudpak-data-operator
placementRef:
  name: placement-policy-ibm-cloudpak-data-operator
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-ibm-cloudpak-data-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-ibm-cloudpak-data-operator
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: cloudpak, operator: In, values: ["ibm"]}
