apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-backup
  namespace: guestbook
spec:
  selector:
    matchLabels:
      app: redis
      role: backup
      tier: backend
      data: local
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: backup
        tier: backend
        data: local
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
