kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"log4shell-app:latest","namespace":"devops"},"fieldPath":"spec.template.spec.containers[?(@.name==\"log4shell-app\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '5134155'
  name: log4shell-app
  generation: 1
  namespace: devops
  labels:
    app: log4shell-app
    app.kubernetes.io/component: log4shell-app
    app.kubernetes.io/instance: log4shell-app
    app.kubernetes.io/name: log4shell-app
    app.kubernetes.io/part-of: log4shell-app-app
    app.openshift.io/runtime-namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: log4shell-app
        deploymentconfig: log4shell-app
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: log4shell-app
          image: >-
            quay.io/smileyfritz/log4shell-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
