---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.clusterName }}
spec:
  clusterName: {{ .Values.clusterName }}
  clusterNamespace: {{ .Values.clusterName }}
  clusterLabels:
    cloud: Amazon
    vendor: OpenShift
    {{- range $key, $val := .Values.extraLabels }}
    {{ $key }}: {{ $val }}
    {{- end }}
  applicationManager:
    enabled: {{ .Values.addOns.applicationManager.enabled }}
  policyController:
    enabled: {{ .Values.addOns.policyController.enabled }}
  searchCollector:
    enabled: {{ .Values.addOns.searchCollector.enabled }}
  certPolicyController:
    enabled: {{ .Values.addOns.certPolicyController.enabled }}
  iamPolicyController:
    enabled: {{ .Values.addOns.iamPolicyController.enabled }}
  version: {{ .Values.addOns.version }}
