# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "acs-demo-bundle-31-08-22"
#   createdAt: 2022-08-30T00:15:01.633492263Z
#   expiresAt: 2023-08-30T00:15:00Z
#   id:        83ed695b-214e-4560-b988-6afcb90d9eb4
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-08-30T00:15:01.633492263Z"
    init-bundle.stackrox.io/expires-at: "2023-08-30T00:15:00Z"
    init-bundle.stackrox.io/id: 83ed695b-214e-4560-b988-6afcb90d9eb4
    init-bundle.stackrox.io/name: acs-demo-bundle-31-08-22
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUO2yz/g/FGvFAaZvWa5rS3tEyQ54wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExMxMDA4MDYzMTcxMzcyNDc1NzM1MB4XDTIyMDgzMDAwMDYwMFoXDTI3MDgy
    OTAwMDYwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExMxMDA4MDYzMTcxMzcyNDc1NzM1MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAECB0GbN40J+kUnSj1zsvbHnAAYVyVZfd6l1uA/PAllkoBOrYb
    Y2ElcTZj0JyCCtbRaaAfAGttq8+SijhdUE/9KqNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLNcedxlBzE9OewdmzjTjoVZiaNT
    MAoGCCqGSM49BAMCA0gAMEUCIGSUV0+AebaVhPOm+94ykCw369TFNPgI35o//+EA
    szLfAiEA8hBWrMuZKOVEnAfSOZIEaJ2r/+Vk1sk5RQ2GKHKkIe4=
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICoDCCAkegAwIBAgIIdPlst22g2/wwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExMxMDA4MDYz
    MTcxMzcyNDc1NzM1MB4XDTIyMDgyOTIzMTUwMFoXDTIzMDgzMDAwMTUwMFowgasx
    LTArBgNVBAoTJDgzZWQ2OTViLTIxNGUtNDU2MC1iOTg4LTZhZmNiOTBkOWViNDEa
    MBgGA1UECwwRQ09MTEVDVE9SX1NFUlZJQ0UxQDA+BgNVBAMMN0NPTExFQ1RPUl9T
    RVJWSUNFOiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHDAa
    BgNVBAUTEzg0Mjg4ODc3MTI2NzQ2Njc1MTYwWTATBgcqhkjOPQIBBggqhkjOPQMB
    BwNCAARkr43zsKbZ2fh6Ol1RLsoAeM6oJgEh6VF8NeP8nezwy+1RQP9cA2rv0KTv
    k80GaebBc8HYfZ01JCsOcFOklxIYo4G3MIG0MA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUS2LB1+Ko77TwdGGFy/SEnh+lsMIwHwYDVR0jBBgwFoAUs1x53GUHMT057B2b
    ONOOhVmJo1MwNQYDVR0RBC4wLIISY29sbGVjdG9yLnN0YWNrcm94ghZjb2xsZWN0
    b3Iuc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0cAMEQCIDEGVsGUOILC1LWgXlyn
    E6ASI1wZegyUcxS9a+fxPfCnAiBDsup3VOeFBXWCYo37Bk2KDgyamnObOMcU4NbQ
    PhJr+g==
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIDw6Q2i2ycH1h5zQ9CoFzWBPu+yHudEaZEMT+mvGDgr+oAoGCCqGSM49
    AwEHoUQDQgAEZK+N87Cm2dn4ejpdUS7KAHjOqCYBIelRfDXj/J3s8MvtUUD/XANq
    79Ck75PNBmnmwXPB2H2dNSQrDnBTpJcSGA==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-08-30T00:15:01.633492263Z"
    init-bundle.stackrox.io/expires-at: "2023-08-30T00:15:00Z"
    init-bundle.stackrox.io/id: 83ed695b-214e-4560-b988-6afcb90d9eb4
    init-bundle.stackrox.io/name: acs-demo-bundle-31-08-22
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUO2yz/g/FGvFAaZvWa5rS3tEyQ54wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExMxMDA4MDYzMTcxMzcyNDc1NzM1MB4XDTIyMDgzMDAwMDYwMFoXDTI3MDgy
    OTAwMDYwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExMxMDA4MDYzMTcxMzcyNDc1NzM1MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAECB0GbN40J+kUnSj1zsvbHnAAYVyVZfd6l1uA/PAllkoBOrYb
    Y2ElcTZj0JyCCtbRaaAfAGttq8+SijhdUE/9KqNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLNcedxlBzE9OewdmzjTjoVZiaNT
    MAoGCCqGSM49BAMCA0gAMEUCIGSUV0+AebaVhPOm+94ykCw369TFNPgI35o//+EA
    szLfAiEA8hBWrMuZKOVEnAfSOZIEaJ2r/+Vk1sk5RQ2GKHKkIe4=
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICtDCCAlqgAwIBAgIJANZJ6enBQcAqMAoGCCqGSM49BAMCMEcxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEcMBoGA1UEBRMTMTAwODA2
    MzE3MTM3MjQ3NTczNTAeFw0yMjA4MjkyMzE1MDBaFw0yMzA4MzAwMDE1MDBaMIGm
    MS0wKwYDVQQKEyQ4M2VkNjk1Yi0yMTRlLTQ1NjAtYjk4OC02YWZjYjkwZDllYjQx
    FzAVBgNVBAsMDlNFTlNPUl9TRVJWSUNFMT0wOwYDVQQDDDRTRU5TT1JfU0VSVklD
    RTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwMR0wGwYDVQQF
    ExQxNTQ0MTEyOTk4NzU5NTQxOTY5MDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
    BDrWA2xAIOOXTtdbSDAU/7OKNHpwy7y+3Tsow3kjb5uKNV7dFS1vpJ0KQkbZGVwy
    c0LNKQVGNVn3FfSIVrYIdfCjgc4wgcswDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
    MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQR
    GK7sZ57mtIhp/KKFSIQTgaKhZzAfBgNVHSMEGDAWgBSzXHncZQcxPTnsHZs4046F
    WYmjUzBMBgNVHREERTBDgg9zZW5zb3Iuc3RhY2tyb3iCE3NlbnNvci5zdGFja3Jv
    eC5zdmOCG3NlbnNvci13ZWJob29rLnN0YWNrcm94LnN2YzAKBggqhkjOPQQDAgNI
    ADBFAiA9KadyNzS9Z2p+rAocvCJ9aMv71qED5sv+7mXHxto8wQIhAJ3CaHkc/sY5
    2R3yfEN6ajkFxdwByFMwBfnafdECn+T3
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIJPghJ2ayWIdOpL+OZfAmUGTqKq+vn42mLVgwlD9TBIvoAoGCCqGSM49
    AwEHoUQDQgAEOtYDbEAg45dO11tIMBT/s4o0enDLvL7dOyjDeSNvm4o1Xt0VLW+k
    nQpCRtkZXDJzQs0pBUY1WfcV9IhWtgh18A==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-08-30T00:15:01.633492263Z"
    init-bundle.stackrox.io/expires-at: "2023-08-30T00:15:00Z"
    init-bundle.stackrox.io/id: 83ed695b-214e-4560-b988-6afcb90d9eb4
    init-bundle.stackrox.io/name: acs-demo-bundle-31-08-22
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwTCCAmagAwIBAgIIA61H/w55+mIwCgYIKoZIzj0EAwIwRzEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYDVQQFExMxMDA4MDYz
    MTcxMzcyNDc1NzM1MB4XDTIyMDgyOTIzMTUwMFoXDTIzMDgzMDAwMTUwMFowgbox
    LTArBgNVBAoTJDgzZWQ2OTViLTIxNGUtNDU2MC1iOTg4LTZhZmNiOTBkOWViNDEi
    MCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTFIMEYGA1UEAww/QURN
    SVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
    MDAwMDAwMDAwMDAwMRswGQYDVQQFExIyNjQ5NDcxMTM4Njk4MzQ4NTAwWTATBgcq
    hkjOPQIBBggqhkjOPQMBBwNCAAQTuuqTOzGJ/2wGNqlssfFSy4eMR67XPqLpDEgj
    xvH3UlKnoO8PPfSz7oN6ZYlzLyMVapnTEmjuJSn2j8qIxCZHo4HHMIHEMA4GA1Ud
    DwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0T
    AQH/BAIwADAdBgNVHQ4EFgQU3xGCStCqZqUcgDj2R616omV8E6MwHwYDVR0jBBgw
    FoAUs1x53GUHMT057B2bONOOhVmJo1MwRQYDVR0RBD4wPIIaYWRtaXNzaW9uLWNv
    bnRyb2wuc3RhY2tyb3iCHmFkbWlzc2lvbi1jb250cm9sLnN0YWNrcm94LnN2YzAK
    BggqhkjOPQQDAgNJADBGAiEApgQ/BI9pvdEXV9NFk/kKHXiKN/s9ATDylsUyLI8/
    Tv0CIQD39MrjSnWuQSNTwcsEbcVzcRI8tAyqKWCdN2wNlXtDrA==
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIHmjBsA0K7KU3JkRbWteEI+5kJAd3kaQxuKHD/5ycm+LoAoGCCqGSM49
    AwEHoUQDQgAEE7rqkzsxif9sBjapbLHxUsuHjEeu1z6i6QxII8bx91JSp6DvDz30
    s+6DemWJcy8jFWqZ0xJo7iUp9o/KiMQmRw==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0jCCAXigAwIBAgIUO2yz/g/FGvFAaZvWa5rS3tEyQ54wCgYIKoZIzj0EAwIw
    RzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRwwGgYD
    VQQFExMxMDA4MDYzMTcxMzcyNDc1NzM1MB4XDTIyMDgzMDAwMDYwMFoXDTI3MDgy
    OTAwMDYwMFowRzEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MRwwGgYDVQQFExMxMDA4MDYzMTcxMzcyNDc1NzM1MFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAECB0GbN40J+kUnSj1zsvbHnAAYVyVZfd6l1uA/PAllkoBOrYb
    Y2ElcTZj0JyCCtbRaaAfAGttq8+SijhdUE/9KqNCMEAwDgYDVR0PAQH/BAQDAgEG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLNcedxlBzE9OewdmzjTjoVZiaNT
    MAoGCCqGSM49BAMCA0gAMEUCIGSUV0+AebaVhPOm+94ykCw369TFNPgI35o//+EA
    szLfAiEA8hBWrMuZKOVEnAfSOZIEaJ2r/+Vk1sk5RQ2GKHKkIe4=
    -----END CERTIFICATE-----
