# This is a StackRox cluster init bundle.
# This bundle can be used for setting up any number of StackRox secured clusters.
# NOTE: This file contains secret data and needs to be handled and stored accordingly.
#
#   name:      "acs-demo-bundle-24-05-22"
#   createdAt: 2022-05-24T03:37:29.378019757Z
#   expiresAt: 2023-05-24T03:37:00Z
#   id:        61578ffd-d41c-490c-a725-0bd524469553
#

apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-05-24T03:37:29.378019757Z"
    init-bundle.stackrox.io/expires-at: "2023-05-24T03:37:00Z"
    init-bundle.stackrox.io/id: 61578ffd-d41c-490c-a725-0bd524469553
    init-bundle.stackrox.io/name: acs-demo-bundle-24-05-22
  creationTimestamp: null
  name: admission-control-tls
stringData:
  admission-control-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICwjCCAmigAwIBAgIJALsJgoBVfK6BMAoGCCqGSM49BAMCMEYxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEbMBkGA1UEBRMSNzQ0NjUw
    NzQwODk4OTMyMDkzMB4XDTIyMDUyNDAyMzcwMFoXDTIzMDUyNDAzMzcwMFowgbwx
    LTArBgNVBAoTJDYxNTc4ZmZkLWQ0MWMtNDkwYy1hNzI1LTBiZDUyNDQ2OTU1MzEi
    MCAGA1UECwwZQURNSVNTSU9OX0NPTlRST0xfU0VSVklDRTFIMEYGA1UEAww/QURN
    SVNTSU9OX0NPTlRST0xfU0VSVklDRTogMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAt
    MDAwMDAwMDAwMDAwMR0wGwYDVQQFExQxMzQ3NzQ0Njg0NzU4NDU3OTIwMTBZMBMG
    ByqGSM49AgEGCCqGSM49AwEHA0IABIeBf+GzeQWf1wxh2Buqt0kGJUZSx/pcTsc3
    yN9ESyDPykEwQnXxyCgAV6/7ixVH4mkmoKQUEqf2oyPQLGSM7zCjgccwgcQwDgYD
    VR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNV
    HRMBAf8EAjAAMB0GA1UdDgQWBBRvcWLPoFcjtF9uTfwxRXBTAVAOYTAfBgNVHSME
    GDAWgBTJWwIHebYnxYMsIcnugrPO6Ip1njBFBgNVHREEPjA8ghphZG1pc3Npb24t
    Y29udHJvbC5zdGFja3JveIIeYWRtaXNzaW9uLWNvbnRyb2wuc3RhY2tyb3guc3Zj
    MAoGCCqGSM49BAMCA0gAMEUCIQCUHmLaiTNgadkTyTqzQZ2p1JwxIwAXVGZD+fj+
    tvQ7PgIgdcSXGQYjZtDjiTXO5RrSDWNZVYqumPq1ewzUIZSRd8k=
    -----END CERTIFICATE-----
  admission-control-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIGeHTRYwmQfPqhZFB6T5XHQcMTwN1zN9JLTcoWIDvpB3oAoGCCqGSM49
    AwEHoUQDQgAEh4F/4bN5BZ/XDGHYG6q3SQYlRlLH+lxOxzfI30RLIM/KQTBCdfHI
    KABXr/uLFUfiaSagpBQSp/ajI9AsZIzvMA==
    -----END EC PRIVATE KEY-----
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0DCCAXagAwIBAgIUYCIKlJ0/9cPgo/CSsLowoaYybswwCgYIKoZIzj0EAwIw
    RjEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYD
    VQQFExI3NDQ2NTA3NDA4OTg5MzIwOTMwHhcNMjIwNTI0MDMyOTAwWhcNMjcwNTIz
    MDMyOTAwWjBGMScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkxGzAZBgNVBAUTEjc0NDY1MDc0MDg5ODkzMjA5MzBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABK5H/YzizPcxXTR/S2rgMV7m/ANpeN/pwAtLX/fWG9i5RoiYh02D
    PHIQNIr8D2B1fqrCiIbH0RxWb/kAO8zSmIOjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTJWwIHebYnxYMsIcnugrPO6Ip1njAK
    BggqhkjOPQQDAgNIADBFAiEAxvXuQEPoezD3UynIbN3nETc3avMniC+9JQgxd2h2
    OZkCIFFmw5tcJIz1fBLpKU+cbiyQDjkgVgvjwbqPN49cPDr8
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-05-24T03:37:29.378019757Z"
    init-bundle.stackrox.io/expires-at: "2023-05-24T03:37:00Z"
    init-bundle.stackrox.io/id: 61578ffd-d41c-490c-a725-0bd524469553
    init-bundle.stackrox.io/name: acs-demo-bundle-24-05-22
  creationTimestamp: null
  name: collector-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0DCCAXagAwIBAgIUYCIKlJ0/9cPgo/CSsLowoaYybswwCgYIKoZIzj0EAwIw
    RjEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYD
    VQQFExI3NDQ2NTA3NDA4OTg5MzIwOTMwHhcNMjIwNTI0MDMyOTAwWhcNMjcwNTIz
    MDMyOTAwWjBGMScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkxGzAZBgNVBAUTEjc0NDY1MDc0MDg5ODkzMjA5MzBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABK5H/YzizPcxXTR/S2rgMV7m/ANpeN/pwAtLX/fWG9i5RoiYh02D
    PHIQNIr8D2B1fqrCiIbH0RxWb/kAO8zSmIOjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTJWwIHebYnxYMsIcnugrPO6Ip1njAK
    BggqhkjOPQQDAgNIADBFAiEAxvXuQEPoezD3UynIbN3nETc3avMniC+9JQgxd2h2
    OZkCIFFmw5tcJIz1fBLpKU+cbiyQDjkgVgvjwbqPN49cPDr8
    -----END CERTIFICATE-----
  collector-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICoTCCAkagAwIBAgIIGEiYUFUoU7AwCgYIKoZIzj0EAwIwRjEnMCUGA1UEAxMe
    U3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYDVQQFExI3NDQ2NTA3
    NDA4OTg5MzIwOTMwHhcNMjIwNTI0MDIzNzAwWhcNMjMwNTI0MDMzNzAwWjCBqzEt
    MCsGA1UEChMkNjE1NzhmZmQtZDQxYy00OTBjLWE3MjUtMGJkNTI0NDY5NTUzMRow
    GAYDVQQLDBFDT0xMRUNUT1JfU0VSVklDRTFAMD4GA1UEAww3Q09MTEVDVE9SX1NF
    UlZJQ0U6IDAwMDAwMDAwLTAwMDAtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMDEcMBoG
    A1UEBRMTMTc0OTgxNTkyNjAyNjk0OTU1MjBZMBMGByqGSM49AgEGCCqGSM49AwEH
    A0IABBrQDCSrmgkDRHiHGclffIdaqqFLZ1tKr1kE6kau0pTvWHy+ldyxckYuoxBC
    gMoyPalGMAoQkyZEXUluZDjTu5ajgbcwgbQwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
    BBRWeAyw0Ut9shn+iK5k1vSA42zIPDAfBgNVHSMEGDAWgBTJWwIHebYnxYMsIcnu
    grPO6Ip1njA1BgNVHREELjAsghJjb2xsZWN0b3Iuc3RhY2tyb3iCFmNvbGxlY3Rv
    ci5zdGFja3JveC5zdmMwCgYIKoZIzj0EAwIDSQAwRgIhAPTvjrhJHFZ25g/reEf8
    tPDoSzogC/29uDUKMI9IfPkdAiEA8/kaQADyz04dmEbzPCfDttVesND1a3HicDaH
    V6Wt+Cg=
    -----END CERTIFICATE-----
  collector-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIEDCZnysWJJ8KRbZZdvB1Etmr1uLozk5ElpMVlp/FT8poAoGCCqGSM49
    AwEHoUQDQgAEGtAMJKuaCQNEeIcZyV98h1qqoUtnW0qvWQTqRq7SlO9YfL6V3LFy
    Ri6jEEKAyjI9qUYwChCTJkRdSW5kONO7lg==
    -----END EC PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    init-bundle.stackrox.io/created-at: "2022-05-24T03:37:29.378019757Z"
    init-bundle.stackrox.io/expires-at: "2023-05-24T03:37:00Z"
    init-bundle.stackrox.io/id: 61578ffd-d41c-490c-a725-0bd524469553
    init-bundle.stackrox.io/name: acs-demo-bundle-24-05-22
  creationTimestamp: null
  name: sensor-tls
stringData:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIB0DCCAXagAwIBAgIUYCIKlJ0/9cPgo/CSsLowoaYybswwCgYIKoZIzj0EAwIw
    RjEnMCUGA1UEAxMeU3RhY2tSb3ggQ2VydGlmaWNhdGUgQXV0aG9yaXR5MRswGQYD
    VQQFExI3NDQ2NTA3NDA4OTg5MzIwOTMwHhcNMjIwNTI0MDMyOTAwWhcNMjcwNTIz
    MDMyOTAwWjBGMScwJQYDVQQDEx5TdGFja1JveCBDZXJ0aWZpY2F0ZSBBdXRob3Jp
    dHkxGzAZBgNVBAUTEjc0NDY1MDc0MDg5ODkzMjA5MzBZMBMGByqGSM49AgEGCCqG
    SM49AwEHA0IABK5H/YzizPcxXTR/S2rgMV7m/ANpeN/pwAtLX/fWG9i5RoiYh02D
    PHIQNIr8D2B1fqrCiIbH0RxWb/kAO8zSmIOjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTJWwIHebYnxYMsIcnugrPO6Ip1njAK
    BggqhkjOPQQDAgNIADBFAiEAxvXuQEPoezD3UynIbN3nETc3avMniC+9JQgxd2h2
    OZkCIFFmw5tcJIz1fBLpKU+cbiyQDjkgVgvjwbqPN49cPDr8
    -----END CERTIFICATE-----
  sensor-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIICtDCCAlmgAwIBAgIJAI4zmm80aNU/MAoGCCqGSM49BAMCMEYxJzAlBgNVBAMT
    HlN0YWNrUm94IENlcnRpZmljYXRlIEF1dGhvcml0eTEbMBkGA1UEBRMSNzQ0NjUw
    NzQwODk4OTMyMDkzMB4XDTIyMDUyNDAyMzcwMFoXDTIzMDUyNDAzMzcwMFowgaYx
    LTArBgNVBAoTJDYxNTc4ZmZkLWQ0MWMtNDkwYy1hNzI1LTBiZDUyNDQ2OTU1MzEX
    MBUGA1UECwwOU0VOU09SX1NFUlZJQ0UxPTA7BgNVBAMMNFNFTlNPUl9TRVJWSUNF
    OiAwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAxHTAbBgNVBAUT
    FDEwMjQ2NzAzMzc5NjA5MzQzMjk1MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
    1fSQG5Oetb29Ku0eHoD+HheBmOWo7vfB9lrFENRN1SwUrxNS73DyN+jJc+Tk2X94
    HF5VN+T02E62VogeyJRnmKOBzjCByzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYw
    FAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFP2Q
    beLkzivEJygQ7VnCNLqxYO1jMB8GA1UdIwQYMBaAFMlbAgd5tifFgywhye6Cs87o
    inWeMEwGA1UdEQRFMEOCD3NlbnNvci5zdGFja3JveIITc2Vuc29yLnN0YWNrcm94
    LnN2Y4Ibc2Vuc29yLXdlYmhvb2suc3RhY2tyb3guc3ZjMAoGCCqGSM49BAMCA0kA
    MEYCIQCgmlTCT0tZ7qV6fR2NddwiKWlGorv1QjaktmBwZjpjuwIhALHw+MpYUPUc
    VrMEOVygj32OCikOfEOUuqrGoewKjQVe
    -----END CERTIFICATE-----
  sensor-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIL4g2K+8Y3ghTb3PmGojGTtmpOCA4zvx1ForKdgYLGnDoAoGCCqGSM49
    AwEHoUQDQgAE1fSQG5Oetb29Ku0eHoD+HheBmOWo7vfB9lrFENRN1SwUrxNS73Dy
    N+jJc+Tk2X94HF5VN+T02E62VogeyJRnmA==
    -----END EC PRIVATE KEY-----
