# This policy that any PoD with the contained=true is tracked.
#
#
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: data-residency-policy
  annotations:
    policy.open-cluster-management.io/standards: Configuration-Management
    policy.open-cluster-management.io/categories: Data Residency
    policy.open-cluster-management.io/controls: Block-all-data-movement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: data-residency-policy
        spec:
          remediationAction: enforce  # will be overridden by remediationAction in parent policy
          severity: high
          namespaceSelector:
#            include: ["simon-test"]
            include: ["*"]
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  labels:
                    data: local
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: data-residency-policy
placementRef:
  name: placement-data-residency-policy
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: data-residency-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-data-residency-policy
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vendor, operator: In, values: ["OpenShift"]}
